// news
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE'

// global language switch
export const COOKIE_LANGUAGE_CHANGE = 'COOKIE_LANGUAGE_CHANGE'
export const LANGUAGE_CHANGED_BY_USER = 'LANGUAGE_CHANGED_BY_USER'
