// main page
export const FETCH_MAIN_SLIDER_REQUEST = 'FETCH_MAIN_SLIDER_REQUEST';
export const FETCH_MAIN_SLIDER_SUCCESS = 'FETCH_MAIN_SLIDER_SUCCESS';
export const FETCH_MAIN_SLIDER_FAILURE = 'FETCH_MAIN_SLIDER_FAILURE';

export const FETCH_MAIN_SCI_SLIDER_REQUEST = 'FETCH_MAIN_SCI_SLIDER_REQUEST';
export const FETCH_MAIN_SCI_SLIDER_SUCCESS = 'FETCH_MAIN_SCI_SLIDER_SUCCESS';
export const FETCH_MAIN_SCI_SLIDER_FAILURE = 'FETCH_MAIN_SCI_SLIDER_FAILURE';

export const FETCH_NEWS_FOR_MAIN_REQUEST = 'FETCH_NEWS_FOR_MAIN_REQUEST';
export const FETCH_NEWS_FOR_MAIN_SUCCESS = 'FETCH_NEWS_FOR_MAIN_SUCCESS';
export const FETCH_NEWS_FOR_MAIN_FAILURE = 'FETCH_NEWS_FOR_MAIN_FAILURE';

// people
export const FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';

// about
export const FETCH_ABOUT_REQUEST = 'FETCH_ABOUT_REQUEST';
export const FETCH_ABOUT_SUCCESS = 'FETCH_ABOUT_SUCCESS';
export const FETCH_ABOUT_FAILURE = 'FETCH_ABOUT_FAILURE';

// vacancies
export const FETCH_VACANCIES_REQUEST = 'FETCH_VACANICES_REQUEST';
export const FETCH_VACANCIES_SUCCESS = 'FETCH_VACANICES_SUCCESS';
export const FETCH_VACANCIES_FAILURE = 'FETCH_VACANICES_FAILURE';

export const FETCH_VACANCIESHH_REQUEST = 'FETCH_VACANICESHH_REQUEST';
export const FETCH_VACANCIESHH_SUCCESS = 'FETCH_VACANICESHH_SUCCESS';
export const FETCH_VACANCIESHH_FAILURE = 'FETCH_VACANICESHH_FAILURE';

export const FETCH_VACANCYHH_REQUEST = 'FETCH_VACANCYHH_REQUEST';
export const FETCH_VACANCYHH_SUCCESS = 'FETCH_VACANCYHH_SUCCESS';
export const FETCH_VACANCYHH_FAILURE = 'FETCH_VACANCYHH_FAILURE';

// team by UID
export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE';

// science groups
export const FETCH_SCI_GROUPS_REQUEST = 'FETCH_SCI_GROUPS_REQUEST';
export const FETCH_SCI_GROUPS_SUCCESS = 'FETCH_SCI_GROUPS_SUCCESS';
export const FETCH_SCI_GROUPS_FAILURE = 'FETCH_SCI_GROUPS_FAILURE'

// research page 
export const FETCH_RESEARCH_PAGE_REQUEST = 'FETCH_RESEARCH_PAGE_REQUEST';
export const FETCH_RESEARCH_PAGE_SUCCESS = 'FETCH_RESEARCH_PAGE_SUCCESS';
export const FETCH_RESEARCH_PAGE_FAILURE = 'FETCH_RESEARCH_PAGE_FAILURE';

// article
export const FETCH_ARTICLE_BY_UID_REQUEST = 'FETCH_ARTICLE_BY_UID_REQUEST';
export const FETCH_ARTICLE_BY_UID_SUCCESS = 'FETCH_ARTICLE_BY_UID_SUCCESS';
export const FETCH_ARTICLE_BY_UID_FAILURE = 'FETCH_ARTICLE_BY_UID_FAILURE';

export const MORE_NEWS_BY_TAG_REQUEST = 'MORE_NEWS_BY_TAG_REQUEST';
export const MORE_NEWS_BY_TAG_SUCCESS = 'MORE_NEWS_BY_TAG_SUCCESS';
export const MORE_NEWS_BY_TAG_FAILURE = 'MORE_NEWS_BY_TAG_FAILURE';

// news
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

// query news by tag
export const FETCH_ARTICLES_BY_TAG_REQUEST = 'FETCH_ARTICLES_BY_TAG_REQUEST';
export const FETCH_ARTICLES_BY_TAG_SUCCESS = 'FETCH_ARTICLES_BY_TAG_SUCCESS';
export const FETCH_ARTICLES_BY_TAG_FAILURE = 'FETCH_ARTICLES_BY_TAG_FAILURE';

// global language switch
export const COOKIE_LANGUAGE_CHANGE = 'COOKIE_LANGUAGE_CHANGE';
export const LANGUAGE_CHANGED_BY_USER = 'LANGUAGE_CHANGED_BY_USER';

// media kit
export const FETCH_PHOTO_GALLERIES_REQUEST = "FETCH_PHOTO_GALLERIES_REQUEST";
export const FETCH_PHOTO_GALLERIES_SUCCESS = "FETCH_PHOTO_GALLERIES_SUCCESS";
export const FETCH_PHOTO_GALLERIES_FAILURE = "FETCH_PHOTO_GALLERIES_FAILURE";

export const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST";
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";

export const FETCH_PRESENTATIONS_REQUEST = "FETCH_PRESENTATIONS_REQUEST";
export const FETCH_PRESENTATIONS_SUCCESS = "FETCH_PRESENTATIONS_SUCCESS";
export const FETCH_PRESENTATIONS_FAILURE = "FETCH_PRESENTATIONS_FAILURE";

// photo gallery
export const FETCH_PHOTO_BY_UID_REQUEST = 'FETCH_PHOTO_BY_UID_REQUEST';
export const FETCH_PHOTO_BY_UID_SUCCESS = 'FETCH_PHOTO_BY_UID_SUCCESS';
export const FETCH_PHOTO_BY_UID_FAILURE = 'FETCH_PHOTO_BY_UID_FAILURE';

// video
export const FETCH_VIDEO_BY_UID_REQUEST = 'FETCH_VIDEO_BY_UID_REQUEST';
export const FETCH_VIDEO_BY_UID_SUCCESS = 'FETCH_VIDEO_BY_UID_SUCCESS';
export const FETCH_VIDEO_BY_UID_FAILURE = 'FETCH_VIDEO_BY_UID_FAILURE';

// event
export const FETCH_EVENT_BY_UID_REQUEST = 'FETCH_EVENT_BY_UID_REQUEST';
export const FETCH_EVENT_BY_UID_SUCCESS = 'FETCH_EVENT_BY_UID_SUCCESS';
export const FETCH_EVENT_BY_UID_FAILURE = 'FETCH_EVENT_BY_UID_FAILURE';

// events
export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

// query events by tag
export const FETCH_EVENTS_BY_TAG_REQUEST = 'FETCH_EVENTS_BY_TAG_REQUEST';
export const FETCH_EVENTS_BY_TAG_SUCCESS = 'FETCH_EVENTS_BY_TAG_SUCCESS';
export const FETCH_EVENTS_BY_TAG_FAILURE = 'FETCH_EVENTS_BY_TAG_FAILURE';

//search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//search authors
export const SEARCH_AUTHORS_REQUEST = 'SEARCH_AUTHORS_REQUEST';
export const SEARCH_AUTHORS_SUCCESS = 'SEARCH_AUTHORS_SUCCESS';
export const SEARCH_AUTHORS_FAILURE = 'SEARCH_AUTHORS_FAILURE';


//publications
export const FETCH_PUBLICATIONS_REQUEST = 'FETCH_PUBLICATIONS_REQUEST';
export const FETCH_PUBLICATIONS_SUCCESS = 'FETCH_PUBLICATIONS_SUCCESS';
export const FETCH_PUBLICATIONS_FAILURE = 'FETCH_PUBLICATIONS_FAILURE';

//search publications buy author
export const SEARCH_PUBLICATION_BY_AUTHOR_REQUEST = 'SEARCH_PUBLICATION_BY_AUTHOR_REQUEST';
export const SEARCH_PUBLICATION_BY_AUTHOR_SUCCESS = 'SEARCH_PUBLICATION_BY_AUTHOR_SUCCESS';
export const SEARCH_PUBLICATION_BY_AUTHOR_FAILURE = 'SEARCH_PUBLICATION_BY_AUTHOR_FAILURE';

