//main page
export const FETCH_MAIN_SLIDER_REQUEST = 'FETCH_MAIN_SLIDER_REQUEST';
export const FETCH_MAIN_SLIDER_SUCCESS = 'FETCH_MAIN_SLIDER_SUCCESS';
export const FETCH_MAIN_SLIDER_FAILURE = 'FETCH_MAIN_SLIDER_FAILURE';

export const FETCH_MAIN_SCI_SLIDER_REQUEST = 'FETCH_MAIN_SCI_SLIDER_REQUEST';
export const FETCH_MAIN_SCI_SLIDER_SUCCESS = 'FETCH_MAIN_SCI_SLIDER_SUCCESS';
export const FETCH_MAIN_SCI_SLIDER_FAILURE = 'FETCH_MAIN_SCI_SLIDER_FAILURE';

export const FETCH_NEWS_FOR_MAIN_REQUEST = 'FETCH_NEWS_FOR_MAIN_REQUEST';
export const FETCH_NEWS_FOR_MAIN_SUCCESS = 'FETCH_NEWS_FOR_MAIN_SUCCESS';
export const FETCH_NEWS_FOR_MAIN_FAILURE = 'FETCH_NEWS_FOR_MAIN_FAILURE';

//people
export const FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST';
export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';

//about
export const FETCH_ABOUT_REQUEST = 'FETCH_ABOUT_REQUEST';
export const FETCH_ABOUT_SUCCESS = 'FETCH_ABOUT_SUCCESS';
export const FETCH_ABOUT_FAILURE = 'FETCH_ABOUT_FAILURE';

//vacancies
export const FETCH_VACANCIES_REQUEST = 'FETCH_VACANICES_REQUEST';
export const FETCH_VACANCIES_SUCCESS = 'FETCH_VACANICES_SUCCESS';
export const FETCH_VACANCIES_FAILURE = 'FETCH_VACANICES_FAILURE';

// team
export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE';

// article
export const FETCH_POST_BY_UID_REQUEST = 'FETCH_POST_BY_UID_REQUEST';
export const FETCH_POST_BY_UID_SUCCESS = 'FETCH_POST_BY_UID_SUCCESS';
export const FETCH_POST_BY_UID_FAILURE = 'FETCH_POST_BY_UID_FAILURE';

// news
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

// query by Tag
export const FETCH_POSTS_BY_TAG_REQUEST = 'FETCH_POSTS_BY_TAG_REQUEST';
export const FETCH_POSTS_BY_TAG_SUCCESS = 'FETCH_POSTS_BY_TAG_SUCCESS';
export const FETCH_POSTS_BY_TAG_FAILURE = 'FETCH_POSTS_BY_TAG_FAILURE';

//global language switch
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
export const COOKIE_LANGUAGE_CHANGE = 'COOKIE_LANGUAGE_CHANGE';

//media kit
export const FETCH_PHOTO_GALLERIES_REQUEST = "FETCH_PHOTO_GALLERIES_REQUEST";
export const FETCH_PHOTO_GALLERIES_SUCCESS = "FETCH_PHOTO_GALLERIES_SUCCESS";
export const FETCH_PHOTO_GALLERIES_FAILURE = "FETCH_PHOTO_GALLERIES_FAILURE";

export const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST";
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";

export const FETCH_PRESENTATIONS_REQUEST = "FETCH_PRESENTATIONS_REQUEST";
export const FETCH_PRESENTATIONS_SUCCESS = "FETCH_PRESENTATIONS_SUCCESS";
export const FETCH_PRESENTATIONS_FAILURE = "FETCH_PRESENTATIONS_FAILURE";

export const FETCH_BRANDING_REQUEST = "FETCH_BRANDING_REQUEST";
export const FETCH_BRANDING_SUCCESS = "FETCH_BRANDING_SUCCESS";
export const FETCH_BRANDING_FAILURE = "FETCH_BRANDING_FAILURE";

//logo 

export const FETCH_LOGO_REQUEST = "FETCH_LOGO_REQUEST";
export const FETCH_LOGO_SUCCESS = "FETCH_LOGO_SUCCESS";
export const FETCH_LOGO_FAILURE = "FETCH_LOGO_FAILURE";

//photo gallery
export const FETCH_PHOTO_BY_UID_REQUEST = 'FETCH_PHOTO_BY_UID_REQUEST';
export const FETCH_PHOTO_BY_UID_SUCCESS = 'FETCH_PHOTO_BY_UID_SUCCESS';
export const FETCH_PHOTO_BY_UID_FAILURE = 'FETCH_PHOTO_BY_UID_FAILURE';

//video
export const FETCH_VIDEO_BY_UID_REQUEST = 'FETCH_VIDEO_BY_UID_REQUEST';
export const FETCH_VIDEO_BY_UID_SUCCESS = 'FETCH_VIDEO_BY_UID_SUCCESS';
export const FETCH_VIDEO_BY_UID_FAILURE = 'FETCH_VIDEO_BY_UID_FAILURE';

//for api test
export const SELECT_POST = 'SELECT_POST';


//next example 
export const TICK = 'TICK';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';